# STOR 320: Methods for Data Science
## EDA Group #4
#### Group members: Aerin Borden, Talya Firestein, Evelyn Galvan, Estella Li, Hannah Tran

## Introduction

[Describe datasets here]

In this notebook, we will perform EDA to understand the data, identify patterns, detect anomalies, and extract insights that could be useful for predictive modeling.

## Objectives

- Understand the structure and content of the dataset.
- Handle missing values appropriately.
- Explore distributions of individual variables.
- Identify key features that influence house prices.

## Dataset Description

Some of the key variables in the dataset include:

[Variable Name]: What it is

# Part 0: Unpack the Data

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
census_2024 = pd.read_csv("https://raw.githubusercontent.com/estellayl/stor320-colab-data/refs/heads/main/census%20data%20(2024).csv")
census_2024.head()

,Label (Grouping),Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,Arizona!!Estimate,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
0,EMPLOYMENT STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Population 16 years and over,"4,160,138","±4,725","4,160,138",(X),"586,083","±1,667","586,083",(X),"6,193,806",...,"4,882,973",(X),"480,483","±2,259","480,483",(X),"2,796,511","±3,432","2,796,511",(X)
2,In labor force,"2,463,085","±17,131",59.2%,±0.4,"390,591","±5,285",66.6%,±0.9,"3,802,740",...,65.4%,±0.3,"311,849","±5,140",64.9%,±1.0,"1,328,934","±15,522",47.5%,±0.6
3,Civilian labor force,"2,447,875","±17,498",58.8%,±0.4,"363,709","±5,489",62.1%,±0.9,"3,778,884",...,65.3%,±0.3,"307,647","±5,376",64.0%,±1.0,"1,325,458","±15,727",47.4%,±0.6
4,Employed,"2,344,294","±17,303",56.4%,±0.4,"342,028","±5,975",58.4%,±1.0,"3,606,425",...,63.3%,±0.3,"297,101","±5,684",61.8%,±1.1,"1,213,487","±16,481",43.4%,±0.6

In [ ]:
census_2024.describe()

,Label (Grouping),Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,Arizona!!Estimate,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
count,145,137,137,137,137,137,137,137,137,137,...,137,137,137,137,137,137,137,137,137,137
unique,122,114,112,109,21,114,113,109,30,114,...,104,20,113,111,112,33,114,113,109,28
top,Civilian employed population 16 years and ...,(X),(X),(X),(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
freq,3,20,20,16,35,20,20,16,35,20,...,16,35,20,20,16,35,20,20,16,35

In [ ]:
glp_data_2024 = pd.read_csv("https://raw.githubusercontent.com/estellayl/stor320-colab-data/refs/heads/main/2024_selected_drugs.csv")
glp_data_2024.head()

,Tot_Prscrbrs,Tot_Clms,Tot_30day_Fills,Tot_Drug_Cst,Tot_Benes,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,GE65_Tot_Benes,LIS_Bene_Cst_Shr,NonLIS_Bene_Cst_Shr
count,516.000000,5.160000e+02,5.160000e+02,5.160000e+02,5.030000e+02,4.900000e+02,4.900000e+02,4.900000e+02,4.530000e+02,5.160000e+02,5.160000e+02
mean,3765.269380,8.407897e+04,1.128049e+05,1.060598e+08,1.670330e+04,6.860067e+04,9.336036e+04,8.738239e+07,1.459241e+04,1.305497e+05,5.920550e+06
std,19112.870444,5.527889e+05,7.447187e+05,6.907456e+08,1.039963e+05,4.373192e+05,5.972459e+05,5.515873e+08,8.586909e+04,8.625156e+05,3.937820e+07
min,1.000000,1.100000e+01,1.100000e+01,8.654230e+03,1.100000e+01,1.100000e+01,1.100000e+01,8.654230e+03,1.100000e+01,0.000000e+00,0.000000e+00
25%,171.500000,7.362500e+02,1.065950e+03,7.875083e+05,2.665000e+02,7.827500e+02,1.164225e+03,7.906309e+05,3.470000e+02,8.840750e+02,4.472609e+04
50%,659.500000,3.528000e+03,4.974550e+03,4.026292e+06,1.161000e+03,3.336000e+03,4.666050e+03,4.282313e+06,1.266000e+03,6.010285e+03,2.884312e+05
75%,2312.750000,3.523325e+04,4.769035e+04,4.576049e+07,7.652500e+03,3.077950e+04,4.357968e+04,4.163561e+07,7.823000e+03,5.291976e+04,2.795217e+06
max,286517.000000,1.041355e+07,1.435345e+07,1.296581e+10,1.951892e+06,8.040161e+06,1.121868e+07,1.010153e+10,1.533376e+06,1.640812e+07,7.558856e+08

In [ ]:
glp_data_2024.describe()

,Tot_Prscrbrs,Tot_Clms,Tot_30day_Fills,Tot_Drug_Cst,Tot_Benes,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,GE65_Tot_Benes,LIS_Bene_Cst_Shr,NonLIS_Bene_Cst_Shr
count,516.000000,5.160000e+02,5.160000e+02,5.160000e+02,5.030000e+02,4.900000e+02,4.900000e+02,4.900000e+02,4.530000e+02,5.160000e+02,5.160000e+02
mean,3765.269380,8.407897e+04,1.128049e+05,1.060598e+08,1.670330e+04,6.860067e+04,9.336036e+04,8.738239e+07,1.459241e+04,1.305497e+05,5.920550e+06
std,19112.870444,5.527889e+05,7.447187e+05,6.907456e+08,1.039963e+05,4.373192e+05,5.972459e+05,5.515873e+08,8.586909e+04,8.625156e+05,3.937820e+07
min,1.000000,1.100000e+01,1.100000e+01,8.654230e+03,1.100000e+01,1.100000e+01,1.100000e+01,8.654230e+03,1.100000e+01,0.000000e+00,0.000000e+00
25%,171.500000,7.362500e+02,1.065950e+03,7.875083e+05,2.665000e+02,7.827500e+02,1.164225e+03,7.906309e+05,3.470000e+02,8.840750e+02,4.472609e+04
50%,659.500000,3.528000e+03,4.974550e+03,4.026292e+06,1.161000e+03,3.336000e+03,4.666050e+03,4.282313e+06,1.266000e+03,6.010285e+03,2.884312e+05
75%,2312.750000,3.523325e+04,4.769035e+04,4.576049e+07,7.652500e+03,3.077950e+04,4.357968e+04,4.163561e+07,7.823000e+03,5.291976e+04,2.795217e+06
max,286517.000000,1.041355e+07,1.435345e+07,1.296581e+10,1.951892e+06,8.040161e+06,1.121868e+07,1.010153e+10,1.533376e+06,1.640812e+07,7.558856e+08

## Part 1: Data cleaning, merging, and visualization (6 points)

In [ ]:
## column names check (1 point)
glp_data_2024 = glp_data_2024.rename(columns={'Prscrbr_Geo_Desc': 'State'})

In [ ]:
## missing data check (1 point)

In [ ]:
## Outlier check (1 point)

In [ ]:
## data merging (1 point)

In [ ]:
## data transformation, normalization, and cleaning (1 point)

In [ ]:
## Exploratory data visualization (1 point)

## Part 2: Answer questions from the proposals (8 points)

Each plot should be followed by a paragraph of explanation and observation.

### Creator: FIRSTNAME LASTNAME

#### Question:

#### Answer:

### Interpreter 1: FIRSTNAME LASTNAME

#### Question:

#### Answer:

### Interpreter 2: FIRSTNAME LASTNAME

#### Question:

#### Answer:

In [ ]:
## Add more cells if your group has more than two interpreters

### Deliverer: FIRSTNAME LASTNAME

#### Question:

#### Answer:

## Part 3: Follow-up Questions (4 points)

### New Questions Based Off Initial Investigation

- Q1: WRITE_QUESTION_HERE
- Q2: WRITE_QUESTION_HERE

## Summary (2 points)

Give a 2 paragraph summary.

Paragraph 1 should describe what you learned about your data from investigating the initial questions. Did you find anything unusual in your data? Did anything surprise you? Which of the initial questions were helpful in leading you to more questions?

Paragraph 2 should summarize what you learned from investigating the follow-up questions. Why are these follow-up questions interesting for investigation? Describe the tables/figures you used to explore answers to these follow-up questions? What did you learn from the tables/figures regarding the follow-up questions you proposed?